title = "London & Newcastle"
languageCode = "en-us"
contentdir = "content"
publishdir = "docs"
builddrafts = false
baseUrl = ""
canonifyurls = true
author = "admin"
theme = "pixyll"
disqusShortname = "london-and-newcastle"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  # google_analytics_id = "XX-XXXXXXXX-X"
  # twitter_username = "username"
  # paginate = 10
