title = "London & Newcastle"
languageCode = "en-us"
contentdir = "content"
publishdir = "docs"
builddrafts = false
baseUrl = "https://alezucca.github.io/londonandnewcastle/"
canonifyurls = true
author = "admin"
theme = "2020"
disqusShortname = "london-and-newcastle"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  # google_analytics_id = "XX-XXXXXXXX-X"
  twitter_username = "AndNewcastle"
  # paginate = 10
